@echo off
:: IntentShell Preferences & Configuration
:: This file stores user preferences and system settings for IntentShell.
:: Generated by IntentShell.

:: --- General Settings ---
:: Default language for IntentShell (multiple language support coming soon, only en available for now)
set LANGUAGE=en

:: --- Theme ---
:: cli_theme: default, dark, light(coming soon, only default available for now)
set CLI_THEME=default
